// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID     *string `json:"id,omitempty"`
	Title  *string `json:"title,omitempty"`
	Author *string `json:"author,omitempty"`
	Review *string `json:"review,omitempty"`
}

type BookInput struct {
	Title  *string `json:"title,omitempty"`
	Author *string `json:"author,omitempty"`
	Review *string `json:"review,omitempty"`
}
